version: '3'

services:
  database:
    container_name: webhook-database
    image: 'mongo:4.4.1'
    ports:
      - '27017:27017'
    volumes:
      - './db-data:/data/db'

  queue:
    container_name: webhook-queue
    image: rabbitmq:3.8.9-management
    ports:
      - 5672:5672
      - 15672:15672

  web:
    container_name: web
    build:
      context: .
      args:
        PROCESS: web
    environment:
      - PORT=8080
      - DATABASE_URL=mongodb://mongo:27017/webhook
      - QUEUE_URL=amqp://localhost"
    ports:
      - 8080:8080
