name: Build perf test

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/webhook-service

jobs:
  test-chrome:
    name: Test chrome
    runs-on: ubuntu-latest
    steps:
      -
        name: Test chrome
        run: /usr/local/bin/chromedriver --version

  build-both-w-qemu:
    name: Build amd64 and arm64 images with qemu
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: production
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.IMAGE_NAME }}:latest

  build-amd64-w-qemu:
    name: Build amd64 image with qemu
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: production
          platforms: linux/amd64
          tags: ${{ env.IMAGE_NAME }}:latest

  build-amd64-wo-qemu:
    name: Build amd64 image without qemu
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: production
          platforms: linux/amd64
          tags: ${{ env.IMAGE_NAME }}:latest

  build-arm64-w-qemu:
    name: Build arm64 image with qemu
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: production
          platforms: linux/arm64
          tags: ${{ env.IMAGE_NAME }}:latest

  build-arm64-wo-qemu:
    name: Build arm64 image without qemu (should fail)
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: production
          platforms: linux/arm64
          tags: ${{ env.IMAGE_NAME }}:latest
