name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          target: production
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/webhook-service:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
